DIRECTORIES:
  QUEUE_DIR: ./queue
  OUT_DIR: ./out
  TMP_DIR: ./tmp
  ORIGINALS_DIR: ./originals
  LOG_DIR: ./logs

ALLOWED_FILE_TYPES:
  - jpg
  - jpeg
  - png

FILE_TYPE_TRANSPARENT: png
FILE_TYPE_NONTRANSPARENT: jpeg

ALWAYS_SAVE_AS:
  - webp

SOURCE_SET:
  - (200, 200)
  - (500, 500)
  - (1000, 1000)

HARD_DELETE_UNKNOWN_TYPES: True
HARD_DELETE_UNPROCESSABLE: True

MAX_IMAGE_PIXELS: 20000000
IGNORE_COMPRESSION_BOMBS: False

DISABLE_LOGGING: False
WEAK: False